NAMES = [
    "Agumemnon the Younger",
    "Agumemnon the Older",
    "Dustin Soot",
    "Dr. Yinz Lubjana",
    "Charles, Son of Eric, Son of Marcus, Third of His Name",
    "Calligula the Immolator",
    "Chowder from Chowder",
    "Reid Gimball",
    "Rich Fillbun",
    "Casper Walcott",
    "Despondius the Dark",
    "Chef Bhoag",
    "Beaumont X Farenheit",
    "Féz Polanski",
    "Gunblade Branson",
    "Ben the Small",
    "CJ the Intimidator",
    "X Æ A-Xvii",
    "Lydia",
    "Heinz Doofenschmirtz",
    "Hog-Poster the Shameless",
    "Gaius Fierricus",
    "Jantach Solarspear",
    "Wick",
    "El Nino",
    "El Nino's Brother",
    "Mk. \"Mark\" Nine",
    "Stinkus the Pestulent",
    "Dr. Steven Brule",
    "Shed Shittley",
    "The Faceless Fiddler",
    "Hyperspace Kamikaze",
    "Code Name: Ghost Terrorist",
    "Professional Jaywalker",
    "Patrick Greenton of Beechshire",
    "Drybo",
    "Smooth Newt",
    "Monologue Egg",
    "Loose Quiche",
    "Propylene Milker",
    "Steward of the Millipedes",
    "Adirondack Dad",
    "Worsmiff",
    "Meat the Warhead",
    "Axomaxo",
    "Scopecuck",
    "Bootleg Scoop",
    "Fascinating Protuberant Rocks",
    "Homegrown Nonsense",
    "my fault og",
    "Worm Church",
    "Fingdom",
    "Anglo-frisian",
    "Homely Chambermaid",
    "Lil Chop, 10pc",
    "Slimedart",
    "Functional Fob",
    "Scoobert Gasolina Mateo",
    "Vermicious Knid"
]

PROLOGUE = "prologue"