NAMES = [
    "Gytha",
    "Gifu",
    "Stery",
    "Aethehrt",
    "Wida",
    "Brude",
    "Thelmund",
    "Eadrid",
    "Ewin",
    "Geoffrey Ethys",
    "Cynre",
    "Berhtre",
    "Rihcta",
    "Ecix",
    "Marey",
    "Aedall",
    "Tiny",
    "Eryn",
    "Ecil",
    "Maly",
    "Kater",
    "Othwulf",
    "Aerert",
    "Aethed",
    "Gerne",
    "Mara",
    "Sueda",
    "Phamas Kesor",
    "Folke",
    "Ethes",
    "Joyce",
    "Walda",
    "Brose",
    "Piersym Growe",
    "Piersym Bedde",
    "Cily Nysell",
    "Drancent",
    "Ryany Mery",
    "Balde",
    "Ergad",
    "Earurg",
    "Wine",
    "Warder",
    "Ausan",
    "Edmugh Hawe",
    "Stomes",
    "Marger Harcey",
    "Aerelm",
    "Eadbun",
    "Brictheue",
    "Maerwe",
    "Geoffry",
    "Giles Forde",
    "Rytha",
    "Eagyth",
    "Eanflead",
    "Sarry Very",
    "Aescwin",
    "Andes",
]

PROLOGUE = "prologue"