NAMES = [
    "Agumemnon the Younger",
    "Agumemnon the Older",
    "Dustin Soot",
    "Dr. Yinz Lubjana",
    "Charles, Son of Eric, Son of Marcus, Third of His Name",
    "Calligula the Immolator",
    "Chowder from Chowder",
    "Reid Gimball",
    "Rich Fillbun",
    "Casper Walcott",
    "Despondius the Dark",
    "Chef Bhoag",
    "Beaumont X Farenheit",
    "Féz Polanski",
    "Gunblade Branson",
    "Ben the Small",
    "CJ the Intimidator",
    "X Æ A-Xvii",
    "Lydia",
    "Heinz Doofenschmirtz",
    "Hog-Poster the Shameless",
    "Gaius Fierricus",
    "Jantach Solarspear",
    "Wick",
    "El Nino",
    "El Nino's Brother",
    "Mk. \"Mark\" Nine",
    "Stinkus the Pestulent",
    "Dr. Steven Brule",
    "Shed Shittley",
    "The Faceless Fiddler",
]

PROLOGUE = "prologue"